# This is a basic workflow to help you get started with Actions

name: GO

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
       - name: Get dependencies
      working-directory: server
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      working-directory: server
      run: go build -v .

    - name: Test
      working-directory: server
      run: go test -v . -cover
      
   # Run Go-linter for code formatting
   - name: Go-linter
    uses: Jerome1337/golint-action@v1.0.2
    with:
      # Path used by golint command
      golint-path: ../server
  
# statically analysis?
    
      # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

    # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.